import express, { Request, Response } from 'express';
import multer from 'multer';
import { sendFile, getUserByEmail } from '../datastore';
import { validateFileRequest } from '../middleware/validateRequest';

const router = express.Router();

const upload = multer({ dest: 'uploads/' });

router.post('/', upload.single('file'), validateFileRequest, (req: Request, res: Response) => {
    const { to, subject, body } = req.body;
    const file = req.file;

    if (!file) {
        return res.status(400).json({ message: 'File upload failed' });
    }

    // const senderEmail = req.user.email;
    const recipient = getUserByEmail(to);

    if (!recipient) {
        return res.status(404).json({ message: 'Recipient not found' });
    }

    sendFile(file.filename, to); // Assuming filename is unique ID generated by multer

    res.status(200).json({ message: 'File sent internally and notification added successfully' });
});

export default router;
