# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './Backend/package-lock.json'
    - run: npm ci
    - run: SERVER_LOG=$(mktemp)
    - run: npm run start >& $SERVER_LOG &
    - run: cat $SERVER_LOG
    - run: timeout 10s grep -q "Server is running on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG)
    - run: timeout -s SIGINT 180s npm run test || (cat $SERVER_LOG && exit 1)
    - run: sleep 2
    - run: cat $SERVER_LOG

  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './Backend/package-lock.json'
    - run: npm ci
    - run: npm run lint

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend
    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './Frontend/package-lock.json'
    - run: npm ci
    - run: npm run build
